package com.hd.service;

import java.util.List;

import com.github.pagehelper.Page;
import com.github.pagehelper.PageInfo;
import com.hd.common.BaseConditionVO;
import com.hd.model.Userbean;
/**
 * 
 * @author admin
 *
 */
public interface IUserService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAR.T_USER
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAR.T_USER
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    int insert(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAR.T_USER
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    int insertSelective(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAR.T_USER
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    Userbean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAR.T_USER
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    int updateByPrimaryKeySelective(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAR.T_USER
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    int updateByPrimaryKey(Userbean record);
   /**
    * 查询所有的用户信息
    * @return
    */
    List<Userbean> queryAll();
	
   PageInfo<Userbean> query(BaseConditionVO vo);
}
