package com.hd.model;

public class Userbean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR.T_USER.ID
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR.T_USER.USERNAME
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR.T_USER.PWD
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR.T_USER.REALNAME
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR.T_USER.SEX
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR.T_USER.DEPID
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    private Integer depid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAR.T_USER.PHONE
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR.T_USER.ID
     *
     * @return the value of CAR.T_USER.ID
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR.T_USER.ID
     *
     * @param id the value for CAR.T_USER.ID
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR.T_USER.USERNAME
     *
     * @return the value of CAR.T_USER.USERNAME
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR.T_USER.USERNAME
     *
     * @param username the value for CAR.T_USER.USERNAME
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR.T_USER.PWD
     *
     * @return the value of CAR.T_USER.PWD
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR.T_USER.PWD
     *
     * @param pwd the value for CAR.T_USER.PWD
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR.T_USER.REALNAME
     *
     * @return the value of CAR.T_USER.REALNAME
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR.T_USER.REALNAME
     *
     * @param realname the value for CAR.T_USER.REALNAME
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR.T_USER.SEX
     *
     * @return the value of CAR.T_USER.SEX
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR.T_USER.SEX
     *
     * @param sex the value for CAR.T_USER.SEX
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR.T_USER.DEPID
     *
     * @return the value of CAR.T_USER.DEPID
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public Integer getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR.T_USER.DEPID
     *
     * @param depid the value for CAR.T_USER.DEPID
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public void setDepid(Integer depid) {
        this.depid = depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAR.T_USER.PHONE
     *
     * @return the value of CAR.T_USER.PHONE
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAR.T_USER.PHONE
     *
     * @param phone the value for CAR.T_USER.PHONE
     *
     * @mbggenerated Mon Mar 13 16:44:13 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}